# Generated by Django 6.0.2 on 2026-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntos', models.IntegerField()),
                ('tipo_juego', models.CharField(choices=[('quiz', 'Quiz de Reciclaje'), ('arrastrar', 'Clasifica Residuos')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-puntos', '-fecha'],
                'indexes': [models.Index(fields=['tipo_juego', '-puntos'], name='principal_p_tipo_ju_3b91f0_idx')],
            },
        ),
    ]
