# Generated by Django 6.0.2 on 2026-02-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('error', 'Error'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('almacenamiento_pct', models.FloatField(help_text='Porcentaje de almacenamiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camara', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('desconectado', 'Desconectado')], max_length=20)),
                ('s_infrarrojo', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('desconectado', 'Desconectado')], max_length=20)),
                ('s_ultrasonico', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('desconectado', 'Desconectado')], max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sensor', models.CharField(choices=[('camara', 'Cámara'), ('infrarrojo', 'Infrarrojo'), ('ultrasonico', 'Ultrasónico'), ('presion', 'Presión')], max_length=20)),
                ('valor', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['tipo_sensor', '-fecha_registro'], name='telemetria__tipo_se_f19574_idx')],
            },
        ),
    ]
