# Generated by Django 6.0.2 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorBotellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Botellas',
                'verbose_name_plural': 'Contadores de Botellas',
                'ordering': ['-fecha'],
            },
        ),
    ]
